name: gradle_dependencies

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Run dependency submission
        uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          use-gradlew: true
          gradle-build-module: |-
            :icons
            :plugin:common
            :plugin:v212
            :plugin:v223
            :plugin:v231
            :plugin:v232
            :plugin:v242
          gradle-build-configuration: |-
            compileClasspath
